target 'PhoneKitDemo', :exclusive => true do
  pod "PhoneKit", :path => "../"
  pod "AFNetworking"
end

target 'Tests', :exclusive => true do
  pod "PhoneKit", :path => "../"

  pod 'Kiwi/XCTest'
end
